import { redirect } from 'next/navigation';
import { verifyOrgAccess } from '@/lib/intel/middleware';
import BriefingDashboard from '@/components/intel/BriefingDashboard';

export default async function BriefingPage({ params }: { params: Promise<{ 'org-slug': string }> }) {
  const { 'org-slug': orgSlug } = await params;
  const access = await verifyOrgAccess(orgSlug);
  if (!access) redirect('/intel/login');

  const { org, member } = access;
  const isAdmin = member.role === 'super_admin' || member.role === 'admin';

  return (
    <div>
      <h1 className="text-2xl font-bold mb-2" style={{ color: 'var(--intel-text)' }}>Intelligence Briefing</h1>
      <p className="text-sm italic opacity-60 mb-6" style={{ color: 'var(--intel-text)' }}>Your weekly intelligence brief. A synthesized overview of developments, upcoming deadlines, new recommendations, trend signals, and research target activity — generated by the analyst based on everything it has ingested and observed.</p>
      <BriefingDashboard orgId={org.id} isAdmin={isAdmin} />
    </div>
  );
}
